"""add document activity tables

Revision ID: 04e87994f75e
Revises: 03f34e5f927c
Create Date: 2026-08-20 12:48:54.505089
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '04e87994f75e'
down_revision: Union[str, None] = '03f34e5f927c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('section', sa.String(length=500), nullable=True),
    sa.Column('web_url', sa.Text(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_author', sa.String(length=200), nullable=True),
    sa.Column('line_count', sa.Integer(), nullable=True),
    sa.Column('is_present', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    op.create_table('document_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('added', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['tracked_document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'day', name='uq_document_activity_document_day')
    )
    op.create_index('ix_document_activity_day', 'document_activity', ['day'], unique=False)
    op.create_table('document_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['tracked_document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_content')
    op.drop_index('ix_document_activity_day', table_name='document_activity')
    op.drop_table('document_activity')
    op.drop_table('tracked_document')
    # ### end Alembic commands ###
