"""add stress test tables

Revision ID: 47a0603e908a
Revises: 3a7e5c37e426
Create Date: 2026-07-28 14:05:50.328683
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '47a0603e908a'
down_revision: Union[str, None] = '3a7e5c37e426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stress_test',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('scenario', sa.String(length=50), nullable=False),
    sa.Column('target_host', sa.String(length=200), nullable=False),
    sa.Column('target_port', sa.Integer(), nullable=False),
    sa.Column('transport', sa.String(length=10), nullable=False),
    sa.Column('cps', sa.Integer(), nullable=False),
    sa.Column('max_calls', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('call_duration', sa.Integer(), nullable=False),
    sa.Column('ramp_up', sa.Integer(), nullable=False),
    sa.Column('ramp_step', sa.Integer(), nullable=False),
    sa.Column('caller_id', sa.String(length=100), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remote_test_id', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stress_test_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stress_test_id', sa.UUID(), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('successful_calls', sa.Integer(), nullable=False),
    sa.Column('failed_calls', sa.Integer(), nullable=False),
    sa.Column('asr_percent', sa.Float(), nullable=False),
    sa.Column('pdd_avg_ms', sa.Float(), nullable=False),
    sa.Column('pdd_p95_ms', sa.Float(), nullable=False),
    sa.Column('setup_time_avg_ms', sa.Float(), nullable=False),
    sa.Column('cps_achieved', sa.Float(), nullable=False),
    sa.Column('retransmissions', sa.Integer(), nullable=False),
    sa.Column('failed_by_code', sa.JSON(), nullable=True),
    sa.Column('packets_sent', sa.Integer(), nullable=False),
    sa.Column('packets_received', sa.Integer(), nullable=False),
    sa.Column('packet_loss_pct', sa.Float(), nullable=False),
    sa.Column('jitter_avg_ms', sa.Float(), nullable=False),
    sa.Column('jitter_max_ms', sa.Float(), nullable=False),
    sa.Column('rtt_avg_ms', sa.Float(), nullable=False),
    sa.Column('rtt_max_ms', sa.Float(), nullable=False),
    sa.Column('mos_score', sa.Float(), nullable=False),
    sa.Column('out_of_order', sa.Integer(), nullable=False),
    sa.Column('throughput_kbps', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('max_concurrent', sa.Integer(), nullable=False),
    sa.Column('ramp_up_curve', sa.JSON(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stress_test_id'], ['stress_test.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_table('stress_test_metrics')
    op.drop_table('stress_test')
    # ### end Alembic commands ###
