"""add config last scan at

Revision ID: 8cef1114a224
Revises: 04e87994f75e
Create Date: 2026-08-20 13:33:42.090949
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8cef1114a224'
down_revision: Union[str, None] = '04e87994f75e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('last_scan_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('config', 'last_scan_at')
    # ### end Alembic commands ###
