"""add project tables

Revision ID: aa2d4bae63d4
Revises: b1c2d3e4f5a6
Create Date: 2026-08-19 11:56:48.655870
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'aa2d4bae63d4'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('stale_days', sa.Integer(), nullable=False),
    sa.Column('budget_warn_pct', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_link',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('file_id', sa.String(length=100), nullable=True),
    sa.Column('is_kpi_source', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_snapshot_project_captured', 'project_snapshot', ['project_id', 'captured_at'], unique=False)
    op.add_column('config', sa.Column('google_sa_key', sa.Text(), nullable=False, server_default=''))
    op.add_column('config', sa.Column('projects_cron', sa.String(length=100), nullable=False, server_default='0 6 * * *'))
    # ### end Alembic commands ###
    # Drop server defaults after backfilling existing rows so the schema matches the
    # model exactly (defaults are applied at the application layer, not the DB layer).
    op.alter_column('config', 'google_sa_key', server_default=None)
    op.alter_column('config', 'projects_cron', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('config', 'projects_cron')
    op.drop_column('config', 'google_sa_key')
    op.drop_index('ix_project_snapshot_project_captured', table_name='project_snapshot')
    op.drop_table('project_snapshot')
    op.drop_table('project_link')
    op.drop_table('project')
    # ### end Alembic commands ###
